/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\theme.ts
 * Command: astryx theme build src\theme.ts
 * CLI: @astryxdesign/cli@0.6.3
 * Core: @astryxdesign/core@0.6.3
 */

/**
 * balabot theme — built by `npx astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { balabotTheme } from './balabot';
 *   import './balabot.css';
 */
export const balabotTheme = {
  name: 'balabot',
  __built: true,
  tokens: {
    "--color-accent": "light-dark(#eaeae6, #1a1b20)",
    "--color-accent-muted": "light-dark(color-mix(in srgb, var(--color-accent) 20%, transparent), color-mix(in srgb, var(--color-accent) 25%, transparent))",
    "--color-on-accent": "light-dark(#1a1a1a, #ececee)",
    "--color-neutral": "light-dark(#1B1B1F1A, #E1E2E833)",
    "--color-background-surface": "light-dark(#ecece9, #111215)",
    "--color-background-body": "light-dark(#fafaf8, #0b0c0e)",
    "--color-overlay": "light-dark(rgba(20, 20, 22, 0.45), rgba(4, 4, 5, 0.72))",
    "--color-overlay-hover": "light-dark(rgba(0, 0, 0, 0.05), rgba(255, 255, 255, 0.05))",
    "--color-overlay-pressed": "light-dark(rgba(0, 0, 0, 0.1), rgba(255, 255, 255, 0.1))",
    "--color-background-muted": "light-dark(#f0f0ed, #141518)",
    "--color-text-primary": "light-dark(#1a1a1a, #ececee)",
    "--color-text-secondary": "light-dark(#6c6c70, #85858a)",
    "--color-text-disabled": "light-dark(#8F909B, #5C5E68)",
    "--color-text-accent": "var(--color-accent)",
    "--color-icon-accent": "var(--color-accent)",
    "--color-icon-primary": "light-dark(#000000, #FBFCFF)",
    "--color-icon-secondary": "light-dark(#2E3039, #C4C6D1)",
    "--color-icon-disabled": "light-dark(#8F909B, #5C5E68)",
    "--color-background-card": "light-dark(#ffffff, #141518)",
    "--color-background-popover": "light-dark(#ffffff, #141518)",
    "--color-background-inverted": "light-dark(#1a1a1a, #f1f1ef)",
    "--color-border": "light-dark(#f0f0ed, #1e2026)",
    "--color-border-emphasized": "light-dark(#e8e8e4, #1c1d22)",
    "--color-skeleton": "light-dark(#A9ABB5, #454650)",
    "--color-track": "light-dark(#A9ABB5, #454650)",
    "--color-shadow": "light-dark(#0000001A, #0000004D)",
    "--color-tint-hover": "light-dark(black, white)",
    "--font-size-4xs": "0.375rem",
    "--font-size-3xs": "0.5rem",
    "--font-size-2xs": "0.5625rem",
    "--font-size-xs": "0.6875rem",
    "--font-size-sm": "0.8125rem",
    "--font-size-base": "1rem",
    "--font-size-lg": "1.1875rem",
    "--font-size-xl": "1.4375rem",
    "--font-size-2xl": "1.75rem",
    "--font-size-3xl": "2.0625rem",
    "--font-size-4xl": "2.5rem",
    "--font-size-5xl": "3rem",
    "--text-heading-1-size": "var(--font-size-2xl)",
    "--text-heading-1-weight": "var(--font-weight-semibold)",
    "--text-heading-1-leading": "1.4286",
    "--text-heading-2-size": "var(--font-size-xl)",
    "--text-heading-2-weight": "var(--font-weight-semibold)",
    "--text-heading-2-leading": "1.3913",
    "--text-heading-3-size": "var(--font-size-lg)",
    "--text-heading-3-weight": "var(--font-weight-semibold)",
    "--text-heading-3-leading": "1.4737",
    "--text-heading-4-size": "var(--font-size-base)",
    "--text-heading-4-weight": "var(--font-weight-semibold)",
    "--text-heading-4-leading": "1.5",
    "--text-heading-5-size": "var(--font-size-sm)",
    "--text-heading-5-weight": "var(--font-weight-semibold)",
    "--text-heading-5-leading": "1.5385",
    "--text-heading-6-size": "var(--font-size-xs)",
    "--text-heading-6-weight": "var(--font-weight-semibold)",
    "--text-heading-6-leading": "1.4545",
    "--text-body-size": "var(--font-size-base)",
    "--text-body-weight": "var(--font-weight-normal)",
    "--text-body-leading": "1.5",
    "--text-large-size": "var(--font-size-lg)",
    "--text-large-weight": "var(--font-weight-semibold)",
    "--text-large-leading": "1.4737",
    "--text-label-size": "var(--font-size-base)",
    "--text-label-weight": "var(--font-weight-medium)",
    "--text-label-leading": "1.5",
    "--text-code-size": "var(--font-size-base)",
    "--text-code-weight": "var(--font-weight-normal)",
    "--text-code-leading": "1.5",
    "--text-supporting-size": "var(--font-size-sm)",
    "--text-supporting-weight": "var(--font-weight-normal)",
    "--text-supporting-leading": "1.5385",
    "--text-display-1-size": "var(--font-size-5xl)",
    "--text-display-1-weight": "var(--font-weight-normal)",
    "--text-display-1-leading": "1.25",
    "--text-display-2-size": "var(--font-size-4xl)",
    "--text-display-2-weight": "var(--font-weight-normal)",
    "--text-display-2-leading": "1.3",
    "--text-display-3-size": "var(--font-size-3xl)",
    "--text-display-3-weight": "var(--font-weight-normal)",
    "--text-display-3-leading": "1.2121",
    "--radius-none": "0px",
    "--radius-inner": "6px",
    "--radius-element": "12px",
    "--radius-container": "18px",
    "--radius-page": "42px",
    "--radius-chat": "42px",
    "--radius-full": "9999px",
    "--font-family-body": "\"Geist Variable\", ui-sans-serif, system-ui, -apple-system, sans-serif",
    "--font-family-heading": "\"Geist Variable\", ui-sans-serif, system-ui, -apple-system, sans-serif",
    "--font-family-code": "\"Geist Mono\", ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace"
  },
  components: {
    "heading": {
      "level:1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-1-size)",
        "fontWeight": "var(--text-heading-1-weight)",
        "lineHeight": "var(--text-heading-1-leading)"
      },
      "level:2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-2-size)",
        "fontWeight": "var(--text-heading-2-weight)",
        "lineHeight": "var(--text-heading-2-leading)"
      },
      "level:3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-3-size)",
        "fontWeight": "var(--text-heading-3-weight)",
        "lineHeight": "var(--text-heading-3-leading)"
      },
      "level:4": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-4-size)",
        "fontWeight": "var(--text-heading-4-weight)",
        "lineHeight": "var(--text-heading-4-leading)"
      },
      "level:5": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-5-size)",
        "fontWeight": "var(--text-heading-5-weight)",
        "lineHeight": "var(--text-heading-5-leading)"
      },
      "level:6": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-6-size)",
        "fontWeight": "var(--text-heading-6-weight)",
        "lineHeight": "var(--text-heading-6-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "text": {
      "type:body": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-body-size)",
        "lineHeight": "var(--text-body-leading)"
      },
      "type:large": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-large-size)",
        "lineHeight": "var(--text-large-leading)"
      },
      "type:label": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-label-size)",
        "lineHeight": "var(--text-label-leading)"
      },
      "type:code": {
        "fontFamily": "var(--font-family-code)",
        "fontSize": "var(--text-code-size)",
        "lineHeight": "var(--text-code-leading)"
      },
      "type:supporting": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-supporting-size)",
        "lineHeight": "var(--text-supporting-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "chat-message-bubble": {
      "base": {
        "borderRadius": "var(--radius-xl)",
        "paddingBlock": "var(--spacing-3)",
        "paddingInline": "var(--spacing-4)"
      }
    },
    "side-nav-item": {
      "base": {
        "borderRadius": "var(--radius-md)"
      }
    }
  },
  __onDark: {
    "tokens": {
      "color-scheme": "dark",
      "--color-text-primary": "var(--color-on-dark)",
      "--color-icon-primary": "var(--color-on-dark)",
      "--color-accent": "var(--color-on-dark)"
    }
  },
  __onLight: {
    "tokens": {
      "color-scheme": "light",
      "--color-text-primary": "var(--color-on-light)",
      "--color-icon-primary": "var(--color-on-light)",
      "--color-accent": "var(--color-on-light)"
    }
  },
  __adaptations: {
    "widthBreakpoints": {
      "sm": 640,
      "md": 768,
      "lg": 1024,
      "xl": 1280,
      "2xl": 1536
    },
    "rules": []
  },
  __axes: {
    "typography": {
      "scale": {
        "base": 16,
        "ratio": 1.2
      },
      "body": {
        "family": "Geist Variable",
        "fallbacks": "ui-sans-serif, system-ui, -apple-system, sans-serif",
        "weight": "normal"
      },
      "heading": {
        "family": "Geist Variable",
        "fallbacks": "ui-sans-serif, system-ui, -apple-system, sans-serif",
        "weight": "semibold"
      },
      "code": {
        "family": "Geist Mono",
        "fallbacks": "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
        "weight": "normal"
      }
    },
    "color": {
      "accent": "#3b82f6",
      "neutralStyle": "neutral",
      "contrast": "high"
    },
    "radius": {
      "base": 4,
      "multiplier": 1.5
    }
  },

};
